---
- name: Create shairport-sync directory {{ shairport_path }}
  ansible.builtin.file:
    path: "{{ shairport_path }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode:  0755
  become: true

