---
- name: apt install Bonjour / mDNS packages
  ansible.builtin.apt:
    name:
      - avahi-daemon
      - avahi-discover
      - avahi-utils
      - libnss-mdns 
      - mdns-scan
    state: latest
  become: true

- name: apt install alsa
  ansible.builtin.apt:
    pkg:
      - alsa
      - alsa-utils
      - alsa-tools
    state: latest
  become: true

- name: add user {{ ansible_user }} to group audio
  ansible.builtin.user:
    name:   "{{ ansible_user }}"
    groups: audio
    append: true
  become: true
